#!/bin/bash


. "${ROLESPEC_LIB}/main"


# Current stable Ansible release
test_ansible_version="stable-2.6"


setup_ansible() {
    install_ansible ${test_ansible_version}

    echo "Ansible config: ${ROLESPEC_ANSIBLE_CONFIG}"
    # Make sure Ansible can use 'become_user' with an unprivileged account
    # See: https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
    cat <<EOF >> "${ROLESPEC_ANSIBLE_CONFIG}"
allow_world_readable_tmpfiles = true
ansible_managed               = This file is managed remotely, all changes will be lost
EOF

    echo "Config contents:"
    cat "${ROLESPEC_ANSIBLE_CONFIG}"
    echo
}

# Test documentation
assert_docs() {
    pip install --upgrade -q pip
    pip install -q sphinx
    pip install git+https://github.com/htgoebel/yaml2rst.git

    cd "${TRAVIS_BUILD_DIR}/docs"
    test -d _static || mkdir -p _static

    yaml2rst ../defaults/main.yml defaults.rst --strip-regex '\s*(:?\[{3}|\]{3})\d?$'
    sphinx-build -n -W -b html -d _build/doctrees . _build/html
    local rc=$?

    cd - > /dev/null
    return ${rc}
}


setup_ansible


# The Letsencrypt account key has to be provided by the user prior of running
# the role. Let's fake it.
test -d /etc/ssl/acme-tiny || sudo mkdir -p /etc/ssl/acme-tiny
test -f /etc/ssl/acme-tiny/account.key || sudo openssl genrsa -out /etc/ssl/acme-tiny/account.key 1024

# Use mock `acme-tiny` script to fake certificate signing process
echo "Copy mock 'acme-tiny' to default \$PATH:"
sudo install -m 755 "$(pwd)/travis/tests/ansible-acme_tiny/mock/acme-tiny.py" /usr/local/bin/acme-tiny
which acme-tiny


#
# Rolespec
#

assert_playbook_runs -vvv

assert_group travis
assert_user_in_group acmetiny travis

assert_path         /etc/ssl/acme-tiny/example.com/example.com.key
assert_permission   /etc/ssl/acme-tiny/example.com/example.com.key 640
assert_path         /etc/ssl/acme-tiny/example.com/example.com.csr
assert_path         /etc/ssl/acme-tiny/example.com/example.com.crt
assert_path         /etc/ssl/acme-tiny/intermediate.crt
assert_path         /etc/ssl/acme-tiny/ca.crt
assert_path         /var/lib/acme-tiny/.ansible.cfg
assert_path         /var/log/acme-tiny


# TODO:
# role is not idempotent yet as every run is triggering a certificate request
#assert_playbook_idempotent

assert_docs

# vim:ft=sh
